[server]
port = 
secret_key = ""
cookie_name = "devcon-token"
cookie_domain = ""
cookie_secure = false

[db]
connection_string = "host= port= user= dbname= password= sslmode="
log_mode = false

[log]
# Log level: ERROR, WARN, INFO or DEBUG (default INFO)
level = ""

[saml]
saml_metadata = ""
saml_issuer = ""
saml_callback = ""
saml_trusted_domains = 

[defaults]
owners = []

[scanengine]
url = ""

[scheduler]
url = ""
# Minimum period time in minutes that a program can be scheduled to run
minimum_interval = 0.1

[sqs]
enabled = true
log_messages = true
polling_interval = 10
wait_time = 20
timeout = 3600
queue_arn = ""
endpoint = ""

[reports]
sns_arn = ""
sns_endpoint = ""
api_base_url = ""
scan_redirect_url= ""
vulcanui_url = ""

[vulcancore]
schema = "http"
host = ""

[vulnerabilitydb]
url = ""
insecure_tls = true

[metrics]
enabled = false


[awscatalogue]
kind = ""
url = ""
key = ""
retries = 4
retry_interval = 2

[globalpolicy]
# This config policy emulates code policy definition.
[globalpolicy.web-scanning-global]
allowed_assettypes = []
blocked_assettypes = []
allowed_checks = ["vulcan-zap"]
blocked_checks = []
excluding_suffixes = ["-experimental"]
