// Code generated by goagen v1.4.3, DO NOT EDIT.
//
// API "Vulcan-API": healthcheck Resource Client
//
// Command:
// $ main

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// ShowHealthcheckPath computes a request path to the show action of healthcheck.
func ShowHealthcheckPath() string {

	return fmt.Sprintf("/api/v1/healthcheck")
}

// A simple HTTP healthcheck.
func (c *Client) ShowHealthcheck(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewShowHealthcheckRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewShowHealthcheckRequest create the request corresponding to the show action endpoint of the healthcheck resource.
func (c *Client) NewShowHealthcheckRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "https"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequestWithContext(ctx, "GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
