// Code generated by goagen v1.4.3, DO NOT EDIT.
//
// API "Vulcan-API": job Resource Client
//
// Command:
// $ main

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// ShowJobPath computes a request path to the show action of job.
func ShowJobPath(jobID string) string {
	param0 := jobID

	return fmt.Sprintf("/api/v1/jobs/%s", param0)
}

// Describe job
func (c *Client) ShowJob(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewShowJobRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewShowJobRequest create the request corresponding to the show action endpoint of the job resource.
func (c *Client) NewShowJobRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "https"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequestWithContext(ctx, "GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.BearerSigner != nil {
		if err := c.BearerSigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}
