// Code generated by goagen v1.4.3, DO NOT EDIT.
//
// API "Vulcan-API": program-scans Resource Client
//
// Command:
// $ main

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// ListProgramScansPath computes a request path to the list action of program-scans.
func ListProgramScansPath(teamID string, programID string) string {
	param0 := teamID
	param1 := programID

	return fmt.Sprintf("/api/v1/teams/%s/programs/%s/scans", param0, param1)
}

// List the scans of a program.
func (c *Client) ListProgramScans(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewListProgramScansRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewListProgramScansRequest create the request corresponding to the list action endpoint of the program-scans resource.
func (c *Client) NewListProgramScansRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "https"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequestWithContext(ctx, "GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.BearerSigner != nil {
		if err := c.BearerSigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}
