// Code generated by goagen v1.4.3, DO NOT EDIT.
//
// API "Vulcan-API": scan Resource Client
//
// Command:
// $ main

package client

import (
	"bytes"
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// CreateScanPath computes a request path to the create action of scan.
func CreateScanPath(teamID string) string {
	param0 := teamID

	return fmt.Sprintf("/api/v1/teams/%s/scans", param0)
}

// Create scan
func (c *Client) CreateScan(ctx context.Context, path string, payload *ScanPayload) (*http.Response, error) {
	req, err := c.NewCreateScanRequest(ctx, path, payload)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewCreateScanRequest create the request corresponding to the create action endpoint of the scan resource.
func (c *Client) NewCreateScanRequest(ctx context.Context, path string, payload *ScanPayload) (*http.Request, error) {
	var body bytes.Buffer
	err := c.Encoder.Encode(payload, &body, "*/*")
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "https"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequestWithContext(ctx, "POST", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	header.Set("Content-Type", "application/json")
	if c.BearerSigner != nil {
		if err := c.BearerSigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// ShowScanPath computes a request path to the show action of scan.
func ShowScanPath(teamID string, scanID string) string {
	param0 := teamID
	param1 := scanID

	return fmt.Sprintf("/api/v1/teams/%s/scans/%s", param0, param1)
}

// Describe scan
func (c *Client) ShowScan(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewShowScanRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewShowScanRequest create the request corresponding to the show action endpoint of the scan resource.
func (c *Client) NewShowScanRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "https"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequestWithContext(ctx, "GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.BearerSigner != nil {
		if err := c.BearerSigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}
