
/*
Copyright 2022 Adevinta
*/

import { readFileSync } from 'fs';
import { GoGenerator } from '@asyncapi/modelina';
import parser from '@asyncapi/parser';

let args = process.argv;
if (args.length != 4) {
  console.error("usage: node gen.js asyncapi_file go_package_name")
  process.exit(1)
}
const sourceFile = args[2];
const goPackageName = args[3];

const docContents = readFileSync(sourceFile);
const generator = new GoGenerator();
const doc = await parser.parse(docContents.toString());
const models = await generator.generate(doc);

console.log(`package ${goPackageName}\n`)
console.log(`// This file is automatically generated, please do not edit.\n`)
for (const model of models) {
  console.log(model.result)
}
