#!/bin/bash

# Copyright 2021 Adevinta

set -e

# install binaries
go install $(go list ./... | grep -v /vendor/)

# create test database and apply migrations
psql -c "CREATE DATABASE vulcanito_test;" -h localhost -U postgres
psql -c "CREATE USER vulcanito_test WITH PASSWORD 'vulcanito_test';" -h localhost -U postgres
psql -c "ALTER USER vulcanito_test WITH SUPERUSER;" -h localhost -U postgres

docker run -q --net=host -v "$PWD"/db:/scripts flyway/flyway:"${FLYWAY_VERSION:-10}-alpine" \
    -user=vulcanito_test -password=vulcanito_test -url=jdbc:postgresql://localhost:5432/vulcanito_test \
    -locations=filesystem:/scripts/sql,filesystem:/scripts/test-sql -baselineOnMigrate=true migrate

psql -c "CREATE DATABASE vulcanito WITH TEMPLATE vulcanito_test OWNER vulcanito_test;" -h localhost -U postgres
