#!/bin/bash

# Copyright 2021 Adevinta

set -e

# go generate and install binaries
go mod vendor
go get github.com/filewalkwithme/impl
go generate -v ./...
go install -v $(go list ./... | grep -v /vendor/)

# create test database and apply migrations
psql -c "CREATE DATABASE vulcanito_test;" -U postgres
psql -c "CREATE USER vulcanito_test WITH PASSWORD 'vulcanito_test';" -U postgres
psql -c "ALTER USER vulcanito_test WITH SUPERUSER;" -U postgres
db/flyway/flyway -user=vulcanito_test -password=vulcanito_test -url=jdbc:postgresql://localhost:5432/vulcanito_test -baselineOnMigrate=true -locations=filesystem:db/sql,filesystem:db/test-sql migrate
psql -c "CREATE DATABASE vulcanito WITH TEMPLATE vulcanito_test OWNER vulcanito_test;" -U postgres
