version: '2.4'

services:
    postgres:
        container_name: vulcanito_db
        image: postgres:13.3-alpine
        command: "postgres -c log_connections=true -c log_min_duration_statement=0"
        ports:
            - "5432:5432"
        expose:
            - "5432"
        volumes:
            - /var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
        environment:
            - POSTGRES_USER=vulcanito
            - POSTGRES_PASSWORD=vulcanito
            - POSTGRES_DB=vulcanito
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        ports:
            - "8000:80"
            - "8443:443"
        links:
            - postgres
        environment:
            - PGADMIN_DEFAULT_EMAIL=vulcanito
            - PGADMIN_DEFAULT_PASSWORD=vulcanito
    # Kafka
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        environment:
            - ZOOKEEPER_CLIENT_PORT=2181
            - ZOOKEEPER_TICK_TIME=2000
    kafka:
        image: confluentinc/cp-kafka:latest
        depends_on:
        - zookeeper
        ports:
        - 29092:29092
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
            - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
